backend/package-lock.json, backend/package.json, backend/src/app.module.ts, backend/src/auth.http, backend/src/auth/auth.controller.spec.ts, backend/src/auth/auth.controller.ts, backend/src/auth/auth.module.ts, backend/src/auth/auth.service.spec.ts, backend/src/auth/auth.service.ts, backend/src/auth/dto/create-auth.dto.ts, backend/src/auth/dto/signin-auth.dto.ts, backend/src/auth/dto/update-auth.dto.ts, backend/src/auth/entities/auth.entity.ts, backend/src/main.ts, backend/src/user/dto/create-user.dto.ts, backend/src/user/dto/update-user.dto.ts, backend/src/user/entities/user.entity.ts, backend/src/user/user.controller.spec.ts, backend/src/user/user.controller.ts, backend/src/user/user.module.ts, backend/src/user/user.service.spec.ts, backend/src/user/user.service.ts
- [BGP-17]
1. auth와 user컴포넌트 생성
2. swagger 설정
3. auth.http 생성
```
@server = http://localhost:3000
POST {{server}}/auth/user
Content-Type: application/json
{
"email" : "11@22",
"password": "22",
"username": "33",
"profileImage": "44"
}
```
swagger 동작 확인
[BGP-17]: https://coli-heo.atlassian.net/browse/BGP-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BE] Auth 라우팅 및 swagger 설정

backend/.gitignore, backend/package-lock.json, backend/package.json, backend/src/app.module.ts, backend/src/auth.http, backend/src/auth/auth.module.ts, backend/src/auth/auth.service.ts, backend/src/user.http, backend/src/user/entities/user.entity.ts, backend/src/user/user.controller.ts, backend/src/user/user.module.ts, backend/src/user/user.repository.ts, backend/src/user/user.service.ts
- [BGP-6]
1. 서버에 DB 설치
2. TypeORM User 연동
3. UserRepository 생성
후에 사용하려면 provider에 UserRepository를 추가하고, `constructor(private readonly userRepository: UserRepository){}`
로 사용하면 된다.
User 생성 확인
[BGP-6]: https://coli-heo.atlassian.net/browse/BGP-6?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BE] DB 설정 및 typeORM 설정

backend/src/auth/auth.controller.ts, backend/src/auth/auth.module.ts, backend/src/auth/auth.service.ts, backend/src/main.ts, backend/src/user/dto/create-user.dto.ts, backend/src/user/dto/update-user.dto.ts, backend/src/user/user.controller.ts, backend/src/user/user.repository.ts, backend/src/user/user.service.ts
- [BGP-17]
- [BGP-20]
1. User 모듈의 사용하지 않는 코드 주석처리, create-user dto 삭제.
2. 회원가입, 로그인 시 쿠키에 email 저장. 서버 메모리에 저장하는 세션에 email 추가.
3. 로그아웃 시 쿠키의 email 값 읽어서 세션에 저장된 email 찾아서 삭제. 쿠키의 email값도 삭제.
유효성 검사, 비밀번호 암호화 진행해야함!
포스트맨과 auth.http 파일에서 실행해서 응답 및 쿠키 확인함.
[BGP-17]: https://coli-heo.atlassian.net/browse/BGP-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-20]: https://coli-heo.atlassian.net/browse/BGP-20?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BE] 기본적인 회원가입, 로그인, 로그아웃 구현

backend/package-lock.json, backend/package.json, backend/src/auth/auth.controller.ts, backend/src/auth/dto/create-auth.dto.ts, backend/src/auth/dto/signin-auth.dto.ts, backend/src/user/entities/user.entity.ts
- [BGP-20]
1. 로그인, 회원가입 시 유효성 검사 pipe를 추가하였습니다.
```
email: 이메일 형식이여야 함
password: String 이고 4~20자 여야함
username: String이여야 함
profileImage: String이고 default는 "" 추후에 수정 예정
isMaster: boolean이여야 함.
```
2. username이 누락된 entity를 수정하였습니다.
```
{
"message": [
"email must be an email",
"password must be longer than or equal to 4 characters",
"isMaster must be a boolean value"
],
"error": "Bad Request",
"statusCode": 400
}
```
[BGP-20]: https://coli-heo.atlassian.net/browse/BGP-20?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BE] 유효성 검사 pipe 추가 및 entity username 추가

backend/package-lock.json, backend/package.json
- [BGP-8]
장애나서 프로그램 꺼져도 다시 실행해주기 위해서 pm2 적용
start, stop 됨.
[BGP-8]: https://coli-heo.atlassian.net/browse/BGP-8?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BE] pm2 추가

frontend/src/api/auth.ts, frontend/src/pages/auth/signin/SigninFooter.tsx, frontend/src/pages/auth/signin/SigninForm.tsx, frontend/src/pages/auth/signup/SignupFooter.tsx, frontend/src/pages/auth/signup/SignupForm.tsx, frontend/src/pages/auth/signup/index.tsx, frontend/src/pages/demo/demoPage.tsx
- [BGP-85]
- 로그인 페이지 네이밍 수정 (loginError => signinError)
- 회원가입 페이지 email, password, username 유효성 검사 및 오류 출력
- 회원가입 실패 시 오류 출력
- signup 함수 api/auth.ts로 분리
- 각 항목 유효성 검사
- 이미 존재하는 회원일때 회원가입 실패, 오류 메세지 출력
[BGP-85]: https://coli-heo.atlassian.net/browse/BGP-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FE] 회원가입 페이지 유효성 검사 추가, CSS 재작업

backend/src/app.module.ts, backend/src/chat/chat.gateway.ts, backend/static/index.html
- [BGP-89]
- [BGP-35]
- [BGP-34]
두번 emit되는 문제 해결.
캠퍼가 마스터 detail 룸에 메세지 보내는것도 추가해서 마스터가 캠퍼의 메세지 확인 가능.
다른 방에 있으면 메세지 오지 않는것 확인.
DB 저장은 아직 안넣음
[BGP-89]: https://coli-heo.atlassian.net/browse/BGP-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-35]: https://coli-heo.atlassian.net/browse/BGP-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-34]: https://coli-heo.atlassian.net/browse/BGP-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BE] index.html 정적파일 수정 및 채팅 테스트

frontend/.eslintrc.cjs, frontend/.prettierrc, frontend/package-lock.json, frontend/package.json, frontend/src/components/button/button.tsx, frontend/src/components/button/likeButton.tsx, frontend/src/components/button/submitButton.tsx, frontend/src/components/checkbox/checkbox.tsx, frontend/src/components/dropdown/dropdown.tsx, frontend/src/components/dropdown/dropdownItem.tsx, frontend/src/components/grid/grid.tsx, frontend/src/components/image/Image.tsx, frontend/src/components/input/input.tsx, frontend/src/components/menu/contentMenu.tsx, frontend/src/components/modal/modal.tsx, frontend/src/components/post/postCard.tsx, frontend/src/components/post/postGrid.tsx, frontend/src/components/slider/imageSlider.tsx, frontend/src/components/text/text.tsx, frontend/src/components/transition/fade.tsx, frontend/src/components/transition/switch.tsx, frontend/src/pages/camps/campPage.tsx, frontend/src/pages/demo/demoPage.tsx, frontend/tsconfig.json
- [BGP-118]
- Airbnb의 코드 컨벤션을 사용한 ESLint 설정 및 Prettier 설정
- 이를 바탕으로 재사용 컴포넌트 부분 포맷팅
[BGP-118]: https://coli-heo.atlassian.net/browse/BGP-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat fe/reusable components

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/auth/dto/create-auth.dto.ts, backend/src/camp/camp.controller.ts, backend/src/camp/camp.repository.ts, backend/src/camp/camp.service.ts, backend/src/camp/dto/create-camp.dto.ts, backend/src/camp/entities/camp.entity.ts, backend/src/camp/entities/subscribe.entity.ts, backend/src/chat/chat.controller.ts, backend/src/chat/chat.gateway.ts, backend/src/chat/chat.module.ts, backend/src/chat/chat.service.ts, backend/src/http/auth.http, backend/src/http/camp.http, backend/src/user/entities/user.entity.ts, backend/src/user/user.controller.ts, backend/src/user/user.repository.ts, backend/src/user/user.service.ts, backend/static/index.html
- [BGP-17]
- [BGP-20]
- [BGP-89]
- [BGP-91]
- [BGP-92]
- [BGP-34]
ERD 변경한대로 회원가입, 로그인, 로그아웃 변경(publicId)
각 채팅 소켓 명세서에 따라 채팅을 보내고 저장하는 로직을 작성했습니다.
[BGP-17]: https://coli-heo.atlassian.net/browse/BGP-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-20]: https://coli-heo.atlassian.net/browse/BGP-20?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-89]: https://coli-heo.atlassian.net/browse/BGP-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-91]: https://coli-heo.atlassian.net/browse/BGP-91?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-92]: …
=> [BE] 채팅 저장 및 ERD 변경 적용

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/http/auth.http
- [BGP-20]
1. 쿠키의 publicId가 session에 있는지 확인
2. 있으면 로그인과 같은 값 리턴 없으면 error과 함께 clear cookie
[BGP-20]: https://coli-heo.atlassian.net/browse/BGP-20?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BE] 로그인 확인 API작성

frontend/src/API/auth.ts, frontend/src/API/camp.ts, frontend/src/API/chat.ts, frontend/src/API/socket.ts, frontend/src/API/subscription.ts, frontend/src/api/auth.ts, frontend/src/api/camp.ts, frontend/src/api/chat.ts, frontend/src/api/socket.ts, frontend/src/api/subscription.ts, frontend/src/constants/URLs.ts, frontend/src/pages/camps/CampInfo.tsx, frontend/src/pages/camps/chat/ChatBox.tsx, frontend/src/pages/camps/edit/password/PasswordPage.tsx, frontend/src/pages/camps/edit/profile/ProfilePage.tsx, frontend/src/pages/camps/post/PostGrid.tsx, frontend/src/pages/camps/post/PostModal.tsx, frontend/src/pages/camps/post/UploadModal.tsx, frontend/src/pages/demo/api/ApiPage.tsx
- meta.PROD의 불리언 값을 이용하여 배포, 개발 환경인지 판단 후 fetch에 쓰일 URL 상수를 설정합니다.
- https://vitejs.dev/guide/env-and-mode.html 를 참고했습니다.
=> [FE] 배포 위한 BASE_URL 수정

.github/workflows/deploy.yml, backend/src/camp/camp.repository.ts, backend/src/camp/camp.service.ts, backend/src/camp/subscription.service.ts, backend/src/http/auth.http, backend/src/http/camp.http, backend/src/http/post.http, backend/src/image/dto/create-image.dto.ts, backend/src/image/entities/image.entity.ts, backend/src/image/image.repository.ts, backend/src/image/image.service.ts, backend/src/main.ts, backend/src/post/comment.repository.ts, backend/src/post/like.repository.ts, backend/src/post/post.controller.ts, backend/src/post/post.service.ts, backend/src/user/dto/update-user.dto.ts, backend/src/user/user.controller.ts, backend/src/user/user.module.ts, backend/src/user/user.repository.ts, backend/src/user/user.service.ts, backend/src/utils/constants.ts
- [BGP-8]
- [BGP-30]
- [BGP-32]
- [BGP-33]
- [BGP-191]
- [BGP-195]
- [BGP-204]
[BGP-8]: https://coli-heo.atlassian.net/browse/BGP-8?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-30]: https://coli-heo.atlassian.net/browse/BGP-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-32]: https://coli-heo.atlassian.net/browse/BGP-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-33]: https://coli-heo.atlassian.net/browse/BGP-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-191]: https://coli-heo.atlassian.net/browse/BGP-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …
=> [BE] 포스트 전체 조회, 상세조회 기능 추가, 동영상 처리 및 깃헙 액션 추가

backend/src/auth/auth.service.ts, backend/src/http/auth.http, backend/src/http/like.http, backend/src/http/post.http, backend/src/http/user.http, backend/src/image/dto/create-image.dto.ts, backend/src/image/entities/image.entity.ts, backend/src/image/image.repository.ts, backend/src/image/image.service.ts, backend/src/post/entities/post.entity.ts, backend/src/post/like.repository.ts, backend/src/post/post.repository.ts, backend/src/post/post.service.ts, backend/src/user/user.controller.ts, backend/src/user/user.service.ts, frontend/src/types/api/post.d.ts
- [BGP-33]
- [BGP-211]
- [BGP-212]
- [BGP-213]
- [BGP-214]
1. 좋아요 다시 눌러도 오류 안나게 처리 Upsert
2. /auth/users, /users 응답 값 수정 및 /users api 생성
3. post 응답 속성 이름을 commentCount, liceCount, pictureCount으로 수정.
4. urls를 사진이 없으면 빈 배열로, 전체 포스트 조회에서 url이 하나만 있어도 배열에 감싸서 전송
5. post 보내줄때 publicId에 작성자 publicId 보내줌
6. 이미지 isImage를 mimetype으로 변경 및 저장
7. 첫 파일이 동영상인 경우 default이미지로 변경하면서 mimetype도 변경
[BGP-33]: https://coli-heo.atlassian.net/browse/BGP-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-211]: https://coli-heo.atlassian.net/browse/BGP-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-212]: https://coli-heo.atlassian.net/browse/BGP-212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
=> [BE] API 수정

backend/src/image/dto/create-image.dto.ts, backend/src/image/entities/image.entity.ts, backend/src/image/image.repository.ts, backend/src/image/image.service.ts, backend/src/post/post.service.ts, backend/src/user/user.repository.ts, backend/src/user/user.service.ts
- [BGP-30]
image에서 imgUrl을 fileUrl로 변경
```
{
"fileUrl": "https://kr.object.ncloudstorage.com/fancamp-images/1-29_3",
"mimetype": "image/png"
},
```
[BGP-30]: https://coli-heo.atlassian.net/browse/BGP-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BE] imageUrl을 fileUrl로 변경

backend/src/auth/auth.service.ts, backend/src/http/auth.http, backend/src/http/like.http, backend/src/http/post.http, backend/src/http/user.http, backend/src/image/dto/create-image.dto.ts, backend/src/image/entities/image.entity.ts, backend/src/image/image.repository.ts, backend/src/image/image.service.ts, backend/src/post/entities/post.entity.ts, backend/src/post/like.repository.ts, backend/src/post/post.repository.ts, backend/src/post/post.service.ts, backend/src/user/user.controller.ts, backend/src/user/user.repository.ts, backend/src/user/user.service.ts, frontend/src/types/api/post.d.ts
- [BGP-]
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
=> [BE] api 수정사항 배포

backend/src/app.module.ts, backend/src/chat/chat.gateway.ts, backend/src/chat/chat.module.ts, backend/src/chat/chat.service.ts, backend/src/notice/notice.gateway.spec.ts, backend/src/notice/notice.gateway.ts, backend/src/notice/notice.module.ts, backend/src/post/post.module.ts, backend/src/post/post.service.ts
- [BGP-185]
- [BGP-186]
1. notice gateway 생성
2. post생성에서 noticePost 호출
3. 마스터가 채팅보낼 때 noticeChat 호출
4. notice namespace로 login event가 들어오면, 구독중인 캠프들 돌면서 join하기
프론트랑 합쳐봐야 합니다.
[BGP-185]: https://coli-heo.atlassian.net/browse/BGP-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-186]: https://coli-heo.atlassian.net/browse/BGP-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BE] 알림 기능 구현

backend/src/camp/camp.controller.ts, backend/src/chat/chat.gateway.ts, backend/src/chat/chat.repository.ts, backend/src/chat/chat.service.ts, backend/src/http/comment.http, backend/src/http/post.http, backend/src/post/comment.repository.ts, backend/src/post/entities/comment.entity.ts, backend/src/post/entities/post.entity.ts, backend/src/post/post.controller.ts, backend/src/post/post.repository.ts, backend/src/post/post.service.ts, backend/src/utils/sentiment.ts
- [BGP-134]
- [BGP-202]
- [BGP-216]
- [BGP-32]
- [BGP-220]
- [BGP-221]
- [BGP-222]
1. 구독 여부 조회 오류 수정
2. 페이지네이션에서 마지막 데이터가 없으면 오류가 아니라 null과 빈배열 반환
3. 감정분석 긍정과 중립 색 교체
4. 댓글 생성 시 publicId와 profileImage 보내주기
5. 댓글 페이지네이션 추가
6. 최신 포스트 API 추가 `GET /posts` 
7. 최신 포스트 API 페이지네이션 적용
8. 마스터가 로그인 중인지 알 수 있는 event 추가
1. 마스터가 들어가면, campName room으로 masterIn event 발생, 배열에 push
2. 캠퍼가 들어갔을 때, 이미 마스터가 있다면 masterIn 이벤트
3. 마스터가 나가면, 배열에서 제거하고 campName room으로 masterout 이벤트
[BGP-134]: https://coli-heo.atlassian.net/browse/BGP-134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-202]: https://coli-heo.atlassian.net/browse/BGP-202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-216]: …
=> [BE] 버그 수정, 기능 수정, 댓글 페이지네이션, 최신 포스트 api 추가, 마스터가 채팅에 있는지 event 추가

frontend/src/components/image/UploadableImage.tsx, frontend/src/components/menu/SideMenu.tsx, frontend/src/components/profile/ProfileImage.tsx, frontend/src/hooks/api/useCommentQuery.ts, frontend/src/hooks/api/useSubscriptionQuery.ts, frontend/src/hooks/useObserver.ts, frontend/src/pages/camps/edit/CampProfileEditPage.tsx, frontend/src/pages/camps/post/PostModalLogic.tsx, frontend/src/pages/camps/post/PostModalTemplate.tsx, frontend/src/pages/demo/api/ApiPage.tsx, frontend/src/pages/demo/components/DemoPage.tsx, frontend/src/pages/feed/FeedCardLogic.tsx, frontend/src/pages/feed/FeedCardTemplate.tsx, frontend/src/pages/feed/FeedPage.tsx, frontend/src/type/api/comment.d.ts
=> [FE] 코멘트 무한스크롤 구현

frontend/src/API/auth.ts
=> [FE] BASE_URL 재수정

backend/src/camp/camp.controller.ts, backend/src/chat/chat.gateway.ts, backend/src/image/image.service.ts, backend/src/notice/notice.gateway.ts, backend/src/post/comment.repository.ts, frontend/src/constants/URLs.ts, frontend/src/pages/home/HomePage.tsx
1. 캠프 컨트롤러 authGuard 범위 수정
2. gateway cors 설정
3. image 저장 이름 형식 변경
4. 댓글 페이지네이션 설정 변경
5. urls vite 추가
6. homepage logo 경로 수정
=> [BE, FE] 데모 전 수정

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/http/auth.http
- [BGP-223]
회원가입 시 이메일, publicId 중복 여부 확인하는 api 생성.
[BGP-223]: https://coli-heo.atlassian.net/browse/BGP-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BE] 회원가입 시 중복 여부 검사

backend/src/app.module.ts, backend/src/camp/camp.controller.ts, backend/src/camp/camp.repository.ts, backend/src/camp/camp.service.ts, backend/src/camp/entities/camp.entity.ts, backend/src/chat/chat.gateway.ts, backend/src/chat/chat.repository.ts, backend/src/image/image.service.ts, backend/src/post/comment.gateway.ts, backend/src/post/post.gateway.ts, backend/src/post/post.module.ts, backend/src/post/post.service.ts, backend/src/utils/logger.middleware.ts, backend/src/utils/sentiment.ts
- [BGP-232]
- [BGP-222]
- [BGP-234]
- [BGP-235]
- [BGP-235]
- [BGP-68]
1. post, comment gateway 생성
2. 페이지에 들어가면 socket 연결
3. 새로운 게 작성되면 소켓을 통해 바로 업데이트 하게 함
4. 채팅 roomName으로 잘못되어 있던 것 수정
5. 동영상이면 isThumb이 true 응답 추가
6. 로거 수정
```
[
{
"content": "썸네일??? ",
"pictureCount": 1,
"isDeleted": false,
"postId": 22,
"createdAt": "2023-12-05T07:14:41.342Z",
"userId": 1,
"campId": 1,
"isMaster": true,
"publicId": "master1",
"likeCount": 0,
"commentCount": 0,
"url": [
{
"fileUrl": "https://kr.object.ncloudstorage.com/fancamp-images/1/22_thumbnail",
"mimetype": "image/png",
"isThumb": true
}
]
},
{
"content": "이미지 업로드 ",
"pictureCount": 1,
"isDeleted": false,
"postId": 21,
"createdAt": "2023-12-05T07:13:34.529Z",
"userId": 1,
"campId": 1,
"isMaster": true,
"publicId": "master1",
"likeCount": 0, …
```
=> [BE] 소켓으로 업데이트 추가, 포스트 썸네일 응답 수정

backend/src/camp/camp.controller.ts, backend/src/camp/camp.repository.ts, backend/src/camp/camp.service.ts, backend/src/camp/subscription.service.ts, backend/src/http/camp.http
- [BGP-233]
- [BGP-25]
- [BGP-204]
- [BGP-240]
- [BGP-241]
- [BGP-242]
1. 구독 여부 return을 오류가 아닌 {isSubscribe:true}로 수정
2. 구독자 수가 0이여도 출력
3. 포스트 수 추가
4. 페이지네이션 추가 40 개 limit
5. 마스터의 publicId, profileImage추가
```
{
"cursor": 0,
"nextCursor": 2,
"camps": [
{
"campId": 1,
"campName": "master1",
"masterId": 1,
"bannerImage": "",
"content": "",
"masterPublicId": "master1",
"masterProfileImage": "",
"subscriptionCount": "1"
},
{
"campId": 2,
"campName": "master2",
"masterId": 2,
"bannerImage": "",
"content": "",
"masterPublicId": "master2",
"masterProfileImage": "",
"subscriptionCount": "0"
}
]
}
```
[BGP-233]: https://coli-heo.atlassian.net/browse/BGP-233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BGP-25]: …
=> [BE] api 수정 및 버그 수정, 구독자 수 반환 추가

frontend/src/components/slider/MediaSlider.tsx, frontend/src/pages/camps/CampInfo.tsx, frontend/src/pages/camps/post/PostModalTemplate.tsx, frontend/src/type/api/camp.d.ts
=> [FE] 슬라이더, 캠프 정보 수정

backend/src/image/image.service.ts, backend/src/post/post.service.ts, frontend/src/components/card/CommentCard.tsx, frontend/src/hooks/api/useCommentQuery.ts, frontend/src/pages/feed/FeedCardTemplate.tsx, frontend/src/pages/search/SearchPage.tsx, frontend/src/route/router.tsx
- 코멘트 리렌더링 최적화
코멘트 타이핑 시 리렌더링 되는 현상을 수정했습니다.
- 썸네일 안보이는 버그 수정
포스트 생성 시 썸네일이 안보이는 버그를 수정했습니다.
=> [FE, BE] 코멘트 리렌더링 최적화, 썸네일 안보이는 버그 수정

backend/src/post/post.service.ts
=> [BE] 비디오 업로드 시 썸네일 안보이는 버그 수정

backend/src/post/post.service.ts
=> [BE]: 파일이 없을때 발생하는 버그 수정

frontend/src/pages/feed/FeedPage.tsx
=> [FE] 이미 지워진 이벤트를 다시 지우는 버그 수정
